AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  IgnoreCopDirectives: true
  IgnoredPatterns:
    - '^#.*'
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20