inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Metrics/LineLength:
  IgnoreCopDirectives: true
  IgnoredPatterns:
    - '^#.*'
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false